{-# LANGUAGE DataKinds #-}
{-# LANGUAGE DisambiguateRecordFields #-}
{-# LANGUAGE DuplicateRecordFields #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE ScopedTypeVariables #-}
{-# LANGUAGE TypeApplications #-}
{-# LANGUAGE TypeOperators #-}
{-# OPTIONS_GHC -Wno-orphans #-}

-- Generated by openapi-model-generator: the concrete registry for NetSuite.
module ConcreteRegistry (netsuiteConcreteOps) where

import Data.List.NonEmpty (NonEmpty (..))
import Data.Maybe (fromMaybe)
import Data.Text (Text)
import qualified Data.Text as T
import qualified Data.UUID.Types as UUID
import GHC.Stack (HasCallStack)

import WebApi.Client.Session (AppIsElem, getSuccessOut)
import WebApi.Contract hiding (OperationId)

import Data.Vector (Vector)

import Dhall.Do.Api.Bridge
import Dhall.Do.Api.Id (FQN (..), OperationId, mkOperationId)
import Dhall.Do.Api.WebApi.Concrete.Binding

import OpenApiModels
import WebApiInstances

instance HsType Currency
instance ToHsVal Currency
instance FromHsVal Currency
instance OverrideType Currency
instance HsSelect Currency

instance HsType CurrencyCollection
instance ToHsVal CurrencyCollection
instance FromHsVal CurrencyCollection
instance HsSelect CurrencyCollection

instance HsType GetCurrencyQP
instance ToHsVal GetCurrencyQP
instance FromHsVal GetCurrencyQP
instance OverrideType GetCurrencyQP

instance HsType ListCurrenciesQP
instance ToHsVal ListCurrenciesQP
instance FromHsVal ListCurrenciesQP
instance OverrideType ListCurrenciesQP

instance HsType NsError
instance ToHsVal NsError
instance FromHsVal NsError
instance HsSelect NsError
instance ErrorText NsError

instance HsType NsLink
instance ToHsVal NsLink
instance FromHsVal NsLink

instance HsType NsObjOErrorPathDetailOErrorQueryParamOErrorHeaderOErrorUrlOErrorCode
instance ToHsVal NsObjOErrorPathDetailOErrorQueryParamOErrorHeaderOErrorUrlOErrorCode
instance FromHsVal NsObjOErrorPathDetailOErrorQueryParamOErrorHeaderOErrorUrlOErrorCode

instance HsType NsObjRefNameId
instance ToHsVal NsObjRefNameId
instance FromHsVal NsObjRefNameId

instance HsType PatchCurrencyQP
instance ToHsVal PatchCurrencyQP
instance FromHsVal PatchCurrencyQP
instance OverrideType PatchCurrencyQP

instance HsType PostCurrencyQP
instance ToHsVal PostCurrencyQP
instance FromHsVal PostCurrencyQP
instance OverrideType PostCurrencyQP

instance HsType PutCurrencyQP
instance ToHsVal PutCurrencyQP
instance FromHsVal PutCurrencyQP
instance OverrideType PutCurrencyQP

_unusedVectorAnchor :: Maybe (Vector ())
_unusedVectorAnchor = Nothing

opIdOf :: (HasCallStack) => Text -> OperationId
opIdOf t = mkOperationId (fromMaybe (error ("bad uuid literal: " <> T.unpack t)) (UUID.fromText t))

mkFqn :: Text -> FQN
mkFqn n = FQN{qualifier = "netsuite" :| [], name = n}

netsuiteConcreteOps :: forall apps. (AppIsElem NetSuite apps) => ConcreteActions apps -> ConcreteActions apps
netsuiteConcreteOps =
    addConcreteOp (opIdOf "0d1e2f30-1111-4a01-8001-000000000002") (mkFqn "getCurrency") (ConcreteOp ((concreteBinding (Right . getSuccessOut)){cbSummary = Just "one currency by internal id (request.path)"} :: ConcreteBinding apps GET NetSuite CurrencyGETRPath (Currency)))
        . addConcreteOp (opIdOf "0d1e2f30-1111-4a01-8001-000000000004") (mkFqn "putCurrency") (ConcreteOp ((concreteBinding (Right . getSuccessOut)){cbSummary = Just "upsert a currency by external id (request.path)", cbRequest = setBody (setField @"links" (Const (mempty :: Vector NsLink)) unsetRecord) (emptyRequest)} :: ConcreteBinding apps PUT NetSuite CurrencyPUTRPath (NsError)))
        . addConcreteOp (opIdOf "0d1e2f30-1111-4a01-8001-000000000006") (mkFqn "deleteCurrency") (ConcreteOp ((concreteBinding (Right . getSuccessOut)){cbSummary = Just "remove a currency by internal id (request.path)"} :: ConcreteBinding apps DELETE NetSuite CurrencyDELETERPath (NsError)))
        . addConcreteOp (opIdOf "0d1e2f30-1111-4a01-8001-000000000005") (mkFqn "patchCurrency") (ConcreteOp ((concreteBinding (Right . getSuccessOut)){cbSummary = Just "update a currency by internal id (request.path)", cbRequest = setBody (setField @"links" (Const (mempty :: Vector NsLink)) unsetRecord) (emptyRequest)} :: ConcreteBinding apps PATCH NetSuite CurrencyPATCHRPath (NsError)))
        . addConcreteOp (opIdOf "0d1e2f30-1111-4a01-8001-000000000001") (mkFqn "listCurrencies") (ConcreteOp ((concreteBinding (Right . getSuccessOut)){cbSummary = Just "the currencies as NetSuite lists them"} :: ConcreteBinding apps GET NetSuite CurrencyRPath (CurrencyCollection)))
        . addConcreteOp (opIdOf "0d1e2f30-1111-4a01-8001-000000000003") (mkFqn "postCurrency") (ConcreteOp ((concreteBinding (Right . getSuccessOut)){cbSummary = Just "insert a currency (the body names it)", cbRequest = setBody (setField @"links" (Const (mempty :: Vector NsLink)) unsetRecord) (emptyRequest)} :: ConcreteBinding apps POST NetSuite CurrencyRPath (NsError)))
