name:                webapi-contract
version:             0.4
github:              "byteally/webapi"
synopsis:            Contracts for webapi library
description:         Contracts for webapi library
homepage:            http://byteally.github.io/webapi/
license:             BSD3
license-file:        LICENSE
author:              Magesh B
maintainer:          magesh85@gmail.com
# copyright:
category:            Web
extra-source-files:
- ChangeLog.md

dependencies:
- base               >= 4.7      && < 5
- text               >= 1.2      && < 1.3
- bytestring         >= 0.10.6.0 && < 0.11
- http-types         >= 0.8.6    && < 0.13

ghc-options:
- -Wall

library:
  source-dirs:      src

tests:
  unit-tests:
    main:           Spec.hs
    source-dirs:    tests
    cpp-options:
    - -DTEST
    dependencies:
    - hspec             >= 2.1  && < 2.6
    - hspec-wai         >= 0.6  && < 0.10
    - webapi-contract
