name:                webapi
version:             0.4
github:              "byteally/webapi"
synopsis:            WAI based library for web api
description:         WAI based library for web api
homepage:            http://byteally.github.io/webapi/
license:             BSD3
license-file:        LICENSE
author:              Magesh B
maintainer:          magesh85@gmail.com
# copyright:
# extra-source-files:
category:            Web
extra-source-files:
- ChangeLog.md

dependencies:
- base               >= 4.7  && < 5
- aeson              >= 0.9  && < 1.4
- blaze-builder      >= 0.4  && < 0.5
- bytestring         >= 0.10 && < 0.11
- bytestring-lexing  == 0.5.*
- case-insensitive   == 1.2.*
- text               >= 1.2  && < 1.3
- time               >= 1.5  && < 1.10
- bytestring-trie    == 0.2.*
- vector             >= 0.10 && < 0.13
- wai-extra          >= 3.0  && < 3.3
- http-types         >= 0.8  && < 0.13
- http-media         >= 0.6  && < 0.8
- webapi-contract    == 0.4.*
- wai                >= 3.0  && < 3.3
- http-client        >= 0.4  && < 0.6
- http-client-tls    >= 0.2  && < 0.4
- cookie             >= 0.4  && < 0.5
- resourcet          >= 1.1  && < 1.3
- exceptions         >= 0.8  && < 1
- network-uri        >= 2.6  && < 2.7
- QuickCheck         >= 2.8  && < 2.13

ghc-options:
- -Wall

library:
  source-dirs: src

tests:
  unit-tests:
    main:           Spec.hs
    source-dirs:    tests
    cpp-options:
    - -DTEST
    dependencies:
    - case-insensitive  == 1.2.*
    - warp
    - hspec             >= 2.1  && < 2.6
    - hspec-wai         >= 0.6  && < 0.10
    - binary            == 0.8.*
    - webapi
